<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.3</version>
	</parent>
	
	<groupId>com.yunyoucloud</groupId>
	<artifactId>plc4x-spring-boot</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>
	
	<modules>
		<module>plc4x-spring-boot-starter</module>
		<module>plc4x-spring-boot-starter-api</module>
	</modules>
	
	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.version>1.0.0</project.version>
		<plc4x.version>0.13.1</plc4x.version>
		<lombok.version>1.18.46</lombok.version>
		<hutool.version>5.8.36</hutool.version>
	</properties>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.apache.plc4x</groupId>
				<artifactId>plc4j-api</artifactId>
				<version>${plc4x.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.apache.plc4x</groupId>
				<artifactId>plc4j-transport-tcp</artifactId>
				<version>${plc4x.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.apache.plc4x</groupId>
				<artifactId>plc4j-driver-opcua</artifactId>
				<version>${plc4x.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.apache.plc4x</groupId>
				<artifactId>plc4j-driver-s7</artifactId>
				<version>${plc4x.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.apache.plc4x</groupId>
				<artifactId>plc4j-driver-modbus</artifactId>
				<version>${plc4x.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
			</dependency>
			
			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-core</artifactId>
				<version>${hutool.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.yunyoucloud</groupId>
				<artifactId>plc4x-spring-boot-starter-api</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	
	<distributionManagement>
		<!-- 正式版本仓库 -->
		<repository>
			<id>yunyou-nexus</id>
			<name>Yunyou Nexus Central</name>
			<url>http://maven.yunyoucloud.local/repository/maven-releases/</url>
		</repository>
	
	</distributionManagement>
</project>
