<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>com.yunyoucloud</groupId>
	<artifactId>plc4x-spring-boot-starter</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>
	
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.3</version>
	</parent>
	
	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<plc4x.version>0.13.1</plc4x.version>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.apache.plc4x</groupId>
			<artifactId>plc4j-api</artifactId>
			<version>${plc4x.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.plc4x</groupId>
			<artifactId>plc4j-transport-tcp</artifactId>
			<version>${plc4x.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.plc4x</groupId>
			<artifactId>plc4j-driver-opcua</artifactId>
			<version>${plc4x.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
		
		<dependency>
			<groupId>com.yunyoucloud</groupId>
			<artifactId>plc4x-spring-boot-starter-api</artifactId>
			<version>1.0.0</version>
		</dependency>
	</dependencies>
	
	<distributionManagement>
		<!-- 正式版本仓库 -->
		<repository>
			<id>yunyou-nexus</id>
			<name>Yunyou Nexus Central</name>
			<url>http://maven.yunyoucloud.local/repository/maven-releases/</url>
		</repository>
	
	</distributionManagement>
	
	<!--	<build>-->
	<!--		<finalName>${project.artifactId}</finalName>-->
	<!--		<plugins>-->
	<!--			<plugin>-->
	<!--				<groupId>org.springframework.boot</groupId>-->
	<!--				<artifactId>spring-boot-maven-plugin</artifactId>-->
	<!--			</plugin>-->
	<!--		</plugins>-->
	<!--	</build>-->

</project>
